# Generated by Django 6.0.8 on 2026-09-13 07:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=220)),
                ("message", models.TextField()),
                ("project_type", models.CharField(blank=True, max_length=120)),
                ("budget", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=110, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional inline icon class/name, e.g. ✦",
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("icon", models.CharField(default="◈", max_length=80)),
                ("short_description", models.CharField(max_length=280)),
                ("full_description", models.TextField(blank=True)),
                (
                    "features",
                    models.TextField(blank=True, help_text="One feature per line."),
                ),
                (
                    "starting_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("site_name", models.CharField(default="Danish Umer", max_length=160)),
                (
                    "headline",
                    models.CharField(
                        default="Full-Stack Web Developer", max_length=220
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="Available for freelance & contract work",
                        max_length=220,
                    ),
                ),
                (
                    "hero_intro",
                    models.TextField(
                        default="I build modern, scalable and high-performing digital experiences for ambitious businesses."
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="Engineering with product thinking.", max_length=180
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        default="I design and build dependable digital products with a sharp focus on clarity, performance, maintainability, and user experience."
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="hello@example.com", max_length=254),
                ),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("location", models.CharField(default="Pakistan", max_length=180)),
                (
                    "availability",
                    models.CharField(
                        default="Open to selected freelance & contract work",
                        max_length=180,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("logo_text", models.CharField(default="DU.", max_length=80)),
                ("resume_url", models.URLField(blank=True)),
                (
                    "footer_description",
                    models.CharField(
                        default="Full-stack engineering for ambitious ideas.",
                        max_length=300,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="Danish Umer — Full-Stack Developer", max_length=180
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="Premium portfolio of Danish Umer, a full-stack web developer building modern digital products.",
                        max_length=300,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("GitHub", "GitHub"),
                            ("LinkedIn", "LinkedIn"),
                            ("X", "X / Twitter"),
                            ("Instagram", "Instagram"),
                            ("Facebook", "Facebook"),
                            ("Website", "Website"),
                        ],
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=80)),
                ("url", models.URLField()),
                ("icon", models.CharField(blank=True, max_length=30)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("short_description", models.CharField(max_length=300)),
                ("full_description", models.TextField()),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/featured/"
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("client", models.CharField(blank=True, max_length=180)),
                (
                    "project_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "live_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "features",
                    models.TextField(blank=True, help_text="One feature per line."),
                ),
                ("challenges", models.TextField(blank=True)),
                ("solutions", models.TextField(blank=True)),
                ("results", models.TextField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                ("featured", models.BooleanField(db_index=True, default=False)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="main.industry",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-project_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="main.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="reviews/"),
                ),
                ("role", models.CharField(blank=True, max_length=150)),
                ("company", models.CharField(blank=True, max_length=150)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField()),
                ("is_approved", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_approved", "is_featured", "-created_at"],
                        name="main_review_is_appr_d337a5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Frontend", "Frontend"),
                            ("Backend", "Backend"),
                            ("Database", "Database"),
                            ("Tools & Platforms", "Tools & Platforms"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("icon", models.ImageField(blank=True, null=True, upload_to="skills/")),
                (
                    "icon_text",
                    models.CharField(
                        blank=True, help_text="Optional emoji/text icon.", max_length=16
                    ),
                ),
                (
                    "skill_level",
                    models.PositiveIntegerField(
                        default=85,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["category", "display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="main_skill_categor_95259d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "category"), name="unique_skill_category"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="main.skill"
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(max_length=180)),
                ("company", models.CharField(max_length=180)),
                ("location", models.CharField(blank=True, max_length=180)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="One responsibility per line."
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="experiences", to="main.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["featured", "display_order"],
                name="main_projec_feature_768dc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["category", "industry"], name="main_projec_categor_94783a_idx"
            ),
        ),
    ]
