# Generated by Django 6.0.8 on 2026-09-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("GitHub", "GitHub"),
                    ("LinkedIn", "LinkedIn"),
                    ("X", "X / Twitter"),
                    ("Instagram", "Instagram"),
                    ("Facebook", "Facebook"),
                    ("Fiverr", "Fiverr"),
                    ("Upwork", "Upwork"),
                    ("Website", "Website"),
                ],
                max_length=40,
            ),
        ),
    ]
