# Generated by Django 6.0.8 on 2026-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_sociallink_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="reply_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="token",
            field=models.UUIDField(
                blank=True, default=None, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["status", "-created_at"], name="main_contac_status_061bb0_idx"
            ),
        ),
    ]
