# Generated by Django 6.0.8 on 2026-09-14 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_contactmessage_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
