# Generated by Django 6.0.8 on 2026-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_contactmessage_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boxed_layout", models.BooleanField(default=False)),
                ("sticky_header", models.BooleanField(default=True)),
                ("minimal_sidebar", models.BooleanField(default=False)),
                ("dark_header", models.BooleanField(default=True)),
                ("dark_sidebar", models.BooleanField(default=True)),
                ("show_banner", models.BooleanField(default=False)),
                (
                    "banner_text",
                    models.CharField(
                        blank=True,
                        default="Welcome to your portfolio CMS.",
                        max_length=240,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin preferences",
                "verbose_name_plural": "Admin preferences",
            },
        ),
    ]
